### ISSUE TITLE
Table is truncated due to large table width

### ISSUE THREAD

**Issue by miked1313** [MicrosoftDocs/fslogix-docs#10] opened 2019-08-22 18:11 UTC
Please reduce the size of the table width so that it fits in this page without a horizontal scrollbar. The Data/Value column in the table is too wide which makes this page very tough to read. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: e794b36e-21f9-5545-cd15-a528f34cbc46
* Version Independent ID: ec93ddfb-158f-0305-f615-1776086d34c1
* Content: [FSLogix Cloud Cache configuration reference - FSLogix](https://docs.microsoft.com/en-us/fslogix/cloud-cache-configuration-reference)
* Content Source: [fslogix-docs/cloud-cache-configuration-reference.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/cloud-cache-configuration-reference.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by dsindona** [comment] 2019-10-04 16:41
Closing issue as this is a duplicate of issue 8

**Closed by dsindona** 2019-10-04 16:41 UTC
Labels: duplicate
