### ISSUE TITLE
Table is truncated due to large table width

### ISSUE THREAD

**Issue by miked1313** [MicrosoftDocs/fslogix-docs#9] opened 2019-08-22 18:11 UTC
Please reduce the size of the table width so that it fits in this page without a horizontal scrollbar. The Data/Value column in the table is too wide which makes this page very tough to read. Thank you.

---
#### Document Details

⚠ *Do not edit this section. It is required for docs.microsoft.com ➟ GitHub issue linking.*

* ID: 978fd40e-7442-8668-fc98-41fe72488264
* Version Independent ID: 3aaec39c-5ea0-fedc-04ea-e3bd4d7784ff
* Content: [Office Container registry configuration settings - FSLogix](https://docs.microsoft.com/en-us/fslogix/office-container-configuration-reference)
* Content Source: [fslogix-docs/office-container-configuration-reference.md](https://github.com/MicrosoftDocs/fslogix-docs-pr/blob/live/fslogix-docs/office-container-configuration-reference.md)
* Product: **fslogix**
* GitHub Login: @DougCoombs
* Microsoft Alias: **docoombs**

**Comment by dsindona** [comment] 2019-10-04 16:41
Closing issue as this is a duplicate of issue 8

**Closed by dsindona** 2019-10-04 16:41 UTC
Labels: duplicate
